//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_SAN_PHAM
    {
        public string MaSanPham { get; set; }
        public string XuatXu { get; set; }
        public string Mau { get; set; }
        public Nullable<int> Size { get; set; }
        public string MoTaSanPham { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<int> GiaBan { get; set; }
    
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
