//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONG_KE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THONG_KE()
        {
            this.CHI_TIET_THONG_KE = new HashSet<CHI_TIET_THONG_KE>();
        }
    
        public string MaDonHang { get; set; }
        public string TenNhanVien { get; set; }
        public string TenKhachHang { get; set; }
        public Nullable<System.DateTime> NgayLapDon { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_THONG_KE> CHI_TIET_THONG_KE { get; set; }
    }
}
